
# SUB CHARTS DEFINITION
mysql:  # use sub-chart name and add its values as children of this key (indented in)
  # Chart Params: https://artifacthub.io/packages/helm/bitnami/mysql
  global:
    defaultStorageClass: "azure-csi"
    compatibility:
      openshift:
        adaptSecurityContext: auto
  commonAnnotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
  nameOverride: "mysql-sub-chart-demo"
  auth:
    existingSecret: "mysql-sub-chart-auth"
    createDatabase: true
    database: "sub-chart-demo"
    username: "sub-chart-demo"


wordpress:  # use sub-chart name and add its values as children of this key (indented in)
  # Chart Params: https://artifacthub.io/packages/helm/bitnami/wordpress
  global:
    defaultStorageClass: "azure-csi"
    compatibility:
      openshift:
        adaptSecurityContext: auto
  commonAnnotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
  nameOverride: "wordpress-sub-chart-demo"
  wordpressUsername: user
  # wordpressPassword: "" # Password retried from secret
  existingSecret: "wordpress-sub-chart-auth"
  wordpressEmail: user@example.com
  wordpressFirstName: FirstName
  wordpressLastName: LastName
  wordpressBlogName: LuqmanBarry's Blog!
  mariadb:
    enabled: false
  externalDatabase:
    host: "mysql-sub-chart-demo"
    port: 3306
    user: "sub-chart-demo"
    password: "sub-chart-demo"
    database: "sub-chart-demo"

# PARENT CHART DEFINITION
namespace: eshop-dev
app:
  name: eshop
  pvc_name: eshop
  pvc_size: 20Gi
  storageClassName: managed-csi
  image: image-registry.openshift-image-registry.svc:5000/openshift/nginx
