---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.mysql.auth.existingSecret }}"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "2"
data:
  mysql-root-password: SDQ0aHNORnIzOHo9M1Ar
  mysql-replication-password: SDQ0aHNSNHIzOHo9M1Ar
  mysql-password: SDRXaHNSNHI4OXo9M1Ar