---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.app.pvc_name }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.app.pvc_size }}"
  storageClassName: {{ .Values.app.storageClassName }}
  volumeMode: Filesystem