---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.wordpress.existingSecret }}"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "2"
data:
  wordpress-password: SDQ0aHNORnIzOHo9M1Ar