---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.app.name }}"
  name: "{{ .Values.app.name }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: "{{ .Values.app.name }}"
  type: LoadBalancer
